from datetime import datetime
from smolagents import tool
from .data_tools import get_active_df


@tool
def generate_report(key_findings: str, recommendations: str = "") -> str:
    """
    Generate a structured markdown analysis report from the loaded dataset and agent findings.

    Args:
        key_findings: A summary of the main findings from the analysis (plain text or bullet points).
        recommendations: Optional actionable recommendations based on the findings.

    Returns:
        A formatted markdown report string.
    """
    df = get_active_df()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    shape = df.shape
    numeric_cols = df.select_dtypes(include="number").columns.tolist()
    categorical_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()
    missing = df.isnull().sum()
    missing_info = (
        "\n".join([f"  - {col}: {cnt} missing" for col, cnt in missing[missing > 0].items()])
        or "  - No missing values"
    )

    report = f"""# Data Analysis Report
**Generated:** {now}

---

## Dataset Overview
| Property | Value |
|---|---|
| Rows | {shape[0]:,} |
| Columns | {shape[1]} |
| Numeric columns | {len(numeric_cols)} |
| Categorical columns | {len(categorical_cols)} |

**Numeric columns:** {', '.join(numeric_cols) if numeric_cols else 'None'}
**Categorical columns:** {', '.join(categorical_cols) if categorical_cols else 'None'}

### Data Quality
{missing_info}

---

## Key Findings
{key_findings}

"""

    if recommendations.strip():
        report += f"""## Recommendations
{recommendations}

"""

    report += "---\n*Report generated by Data Analysis Agent*\n"
    return report
